### PR TITLE
Fleet

### PR DESCRIPTION
**Pull request by ShaneClancy**
Added front-end buttons that change based on game-state.

### CODE REVIEW

**Comment by lunng** [comment]
Button should only appear after two ships have been destroyed.

**Comment by lunng** [comment]
Also need buttons and handlers for north, south, east, and west movement directions.

**Comment by lunng** [comment]
Ship translation logic works for West.

**Comment by olsencar** [comment]
All travis checks pass. Buttons look nice. Good job!

**Pull request merged**
